test

diff --git a/.github/workflows/merge-files.yaml b/.github/workflows/merge-files.yaml
--- a/.github/workflows/merge-files.yaml
+++ b/.github/workflows/merge-files.yaml
@@ -1,141 +1,39 @@
-# name: merge-files
-
-# on:
-#   workflow_run:
-#     workflows: [ci-1-upload, ci-2-upload, ci-3-upload]
-#     types:
-#       - completed
-#     branches:
-#       - main
-
-# jobs:
-#   merge-files:
-#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
-#     name: Download and merge files
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Wait for ci-1-upload, ci-2-upload, and ci-3-upload to complete
-#         uses: lewagon/wait-on-check-action@v1.3.4
-#         with:
-#           ref: ${{ github.sha }}
-#           check-name: |
-#             Upload file 1 /.*
-#             Upload file 2 /.*
-#             Upload file 3 /.*
-#           repo-token: ${{ secrets.GITHUB_TOKEN }}
-#           wait-interval: 10
-#           allowed-conclusions: success
-
-#       - uses: actions/checkout@v3
-#         with:
-#           submodules: true
-
-#       - name: list files
-#         run: ls -l extracted/
-
-#       - name: Download files from 1st workflow
-#         uses: dawidd6/action-download-artifact@v6
-#         with:
-#           workflow: ci-1-upload.yml
-#           name: test-file-1st-run.*
-#           path: extracted/
-#           name_is_regexp: true
-#           search_artifacts: true
-
-#       - name: Download files from 2nd workflow
-#         uses: dawidd6/action-download-artifact@v6
-#         with:
-#           workflow: ci-2-upload.yml
-#           name: test-file-2nd-run.*
-#           path: extracted/
-#           name_is_regexp: true
-#           search_artifacts: true
-
-#       - name: Download files from 3rd workflow
-#         uses: dawidd6/action-download-artifact@v6
-#         with:
-#           workflow: ci-3-upload.yml
-#           name: test-file-3rd-run.*
-#           name_is_regexp: true
-#           path: extracted/
-#           search_artifacts: true
-
-#       - name: list files after download
-#         run: ls -l extracted/
-
-
 name: merge-files
 
 on:
-  push:
-    branches: [main]
+  workflow_run:
+    workflows: [ci-1-upload, ci-2-upload, ci-3-upload]
+    types:
+      - completed
+    branches:
+      - "*"
 
 jobs:
   merge-files:
-    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     name: Download and merge files
     runs-on: ubuntu-latest
-    timeout-minutes: 60
     steps:
+      - name: Wait for ci-1-upload, ci-2-upload, and ci-3-upload to complete
+        uses: lewagon/wait-on-check-action@v1.3.4
+        with:
+          ref: ${{ github.sha }}
+          check-name: |
+            Upload file 1 /.*
+            Upload file 2 /.*
+            Upload file 3 /.*
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          wait-interval: 10
+          allowed-conclusions: success
+
       - uses: actions/checkout@v3
         with:
           submodules: true
-
-      - name: Check if all required workflows completed successfully
-        id: check-workflows
-        run: |
-          workflows=("ci-1-upload" "ci-2-upload" "ci-3-upload")
-          max_retries=600  # Set a max retry limit (e.g., 600 retries with 1-second intervals)
-          interval=1      # Set interval in seconds between retries
-          all_completed=false
-          any_succeeded=false
-
-          commit_sha=$(git rev-parse HEAD)  # Get the current commit SHA
-
-          for (( i=0; i<$max_retries; i++ )); do
-            all_completed=true
-            any_succeeded=false
-            for workflow in "${workflows[@]}"; do
-              conclusion=$(gh run list --workflow=$workflow --branch=main --json conclusion,headSha | jq -r --arg sha "$commit_sha" '.[] | select(.headSha == $sha) | .conclusion')
-              if [[ "$conclusion" == "success" ]]; then
-                any_succeeded=true
-              else
-                all_completed=false
-              fi
-            done
-
-            if [[ "$all_completed" == "true" ]]; then
-              echo "All workflows completed successfully for commit $commit_sha."
-              echo "all_succeeded=true" >> $GITHUB_ENV
-              break
-            fi
-
-            if [[ "$i" -eq $((max_retries - 1)) ]]; then
-              # If we've reached the max retries, check if at least one workflow has succeeded
-              if [[ "$any_succeeded" == "true" ]]; then
-                echo "At least one workflow succeeded for commit $commit_sha."
-                echo "some_succeeded=true" >> $GITHUB_ENV
-              else
-                echo "Timeout waiting for workflows to complete for commit $commit_sha. Exiting."
-                exit 1
-              fi
-            else
-              sleep $interval
-            fi
-          done
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-
-      - name: Continue only if all workflows succeeded
-        if: ${{ env.all_succeeded == 'true' }}
-        run: echo "All workflows completed successfully. Proceeding with file merge."
 
       - name: list files
         run: ls -l extracted/
 
       - name: Download files from 1st workflow
-        if: ${{ env.all_succeeded == 'true' }}
         uses: dawidd6/action-download-artifact@v6
         with:
           workflow: ci-1-upload.yml
@@ -145,7 +43,6 @@ jobs:
           search_artifacts: true
 
       - name: Download files from 2nd workflow
-        if: ${{ env.all_succeeded == 'true' }}
         uses: dawidd6/action-download-artifact@v6
         with:
           workflow: ci-2-upload.yml
@@ -155,7 +52,6 @@ jobs:
           search_artifacts: true
 
       - name: Download files from 3rd workflow
-        if: ${{ env.all_succeeded == 'true' }}
         uses: dawidd6/action-download-artifact@v6
         with:
           workflow: ci-3-upload.yml
@@ -165,5 +61,109 @@ jobs:
           search_artifacts: true
 
       - name: list files after download
-        if: ${{ env.all_succeeded == 'true' }}
         run: ls -l extracted/
+
+
+# name: merge-files
+
+# on:
+#   push:
+#     branches: [main]
+
+# jobs:
+#   merge-files:
+#     # if: ${{ github.event.workflow_run.conclusion == 'success' }}
+#     name: Download and merge files
+#     runs-on: ubuntu-latest
+#     timeout-minutes: 60
+#     steps:
+#       - uses: actions/checkout@v3
+#         with:
+#           submodules: true
+
+#       - name: Check if all required workflows completed successfully
+#         id: check-workflows
+#         run: |
+#           workflows=("ci-1-upload" "ci-2-upload" "ci-3-upload")
+#           max_retries=600  # Set a max retry limit (e.g., 600 retries with 1-second intervals)
+#           interval=1      # Set interval in seconds between retries
+#           all_completed=false
+#           any_succeeded=false
+
+#           commit_sha=$(git rev-parse HEAD)  # Get the current commit SHA
+
+#           for (( i=0; i<$max_retries; i++ )); do
+#             all_completed=true
+#             any_succeeded=false
+#             for workflow in "${workflows[@]}"; do
+#               conclusion=$(gh run list --workflow=$workflow --branch=main --json conclusion,headSha | jq -r --arg sha "$commit_sha" '.[] | select(.headSha == $sha) | .conclusion')
+#               if [[ "$conclusion" == "success" ]]; then
+#                 any_succeeded=true
+#               else
+#                 all_completed=false
+#               fi
+#             done
+
+#             if [[ "$all_completed" == "true" ]]; then
+#               echo "All workflows completed successfully for commit $commit_sha."
+#               echo "all_succeeded=true" >> $GITHUB_ENV
+#               break
+#             fi
+
+#             if [[ "$i" -eq $((max_retries - 1)) ]]; then
+#               # If we've reached the max retries, check if at least one workflow has succeeded
+#               if [[ "$any_succeeded" == "true" ]]; then
+#                 echo "At least one workflow succeeded for commit $commit_sha."
+#                 echo "some_succeeded=true" >> $GITHUB_ENV
+#               else
+#                 echo "Timeout waiting for workflows to complete for commit $commit_sha. Exiting."
+#                 exit 1
+#               fi
+#             else
+#               sleep $interval
+#             fi
+#           done
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+#       - name: Continue only if all workflows succeeded
+#         if: ${{ env.all_succeeded == 'true' }}
+#         run: echo "All workflows completed successfully. Proceeding with file merge."
+
+#       - name: list files
+#         run: ls -l extracted/
+
+#       - name: Download files from 1st workflow
+#         if: ${{ env.all_succeeded == 'true' }}
+#         uses: dawidd6/action-download-artifact@v6
+#         with:
+#           workflow: ci-1-upload.yml
+#           name: test-file-1st-run.*
+#           path: extracted/
+#           name_is_regexp: true
+#           search_artifacts: true
+
+#       - name: Download files from 2nd workflow
+#         if: ${{ env.all_succeeded == 'true' }}
+#         uses: dawidd6/action-download-artifact@v6
+#         with:
+#           workflow: ci-2-upload.yml
+#           name: test-file-2nd-run.*
+#           path: extracted/
+#           name_is_regexp: true
+#           search_artifacts: true
+
+#       - name: Download files from 3rd workflow
+#         if: ${{ env.all_succeeded == 'true' }}
+#         uses: dawidd6/action-download-artifact@v6
+#         with:
+#           workflow: ci-3-upload.yml
+#           name: test-file-3rd-run.*
+#           name_is_regexp: true
+#           path: extracted/
+#           search_artifacts: true
+
+#       - name: list files after download
+#         if: ${{ env.all_succeeded == 'true' }}
+#         run: ls -l extracted/
